apiVersion: core.choreo.dev/v1beta1
kind: ComponentConfig
metadata:
  name: Travel Booking
  projectName: Travel
  annotations:
    componentType: Service
spec:
  # +optional Build instructions for the component.
  build:
    # +required Name of the branch. This is used to identify the corresponding deployment track.
    branch: main
  # +optional Incoming connection details for the component (AKA Endpoints).
  inbound:
    - name: EmployeeTravelBooking
      port: 8081
      type: REST
      networkVisibility: Public
      context: /travelmgt/v1
      schemaFilePath: openapi.json
  outbound:
    serviceReferences:
     - name: choreo:///apifirst/test1022/employee-svc2/ad088/v1/PUBLIC
       connectionConfig: 01ef9071-f94c-1350-8bdd-c18abfcb0f40
       env: 
       - from: ServiceURL
         to: SERVICE_URL
       - from: ConsumerKey
         to: CLIENT_ID
       - from: ConsumerSecret
         to: CLIENT_SECRET
       - from: TokenURL
         to: TOKEN_URL

