apiVersion: core.choreo.dev/v1alpha1
kind: ComponentConfig
metadata:
  name: Travel Booking
  projectName: Travel
  annotations:
    componentType: Service
spec:
  build:
    branch: main
  inbound:
    - name: EmployeeTravelBookingAPI
      port: 8081
      type: REST
      networkVisibility: Public
      context: /travelmgt/v1
      schemaFilePath: openapi.json
  outbound:
    serviceReferences:
    - name: choreo:///apifirst/test514/ufgatw/ad088/v1/PUBLIC
      connectionConfig: 01ef11dc-a6c2-13f0-b2f5-fbfcbcf89088
      env:
      - from: ServiceURL
        to: <YOUR_ENV_VARIABLE_NAME_HERE>
      - from: ConsumerKey
        to: <YOUR_ENV_VARIABLE_NAME_HERE>
      - from: ConsumerSecret
        to: <YOUR_ENV_VARIABLE_NAME_HERE>
      - from: TokenURL
        to: <YOUR_ENV_VARIABLE_NAME_HERE>
